export enum AccountStatus {
  ONBOARDING = 'ONBOARDING',
  SUBMISSION_FAILED = 'SUBMISSION_FAILED',
  SUBMITTED = 'SUBMITTED',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}
